// GENERATED FILE - DO NOT EDIT
// Generated by flutter gen-l10n
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'app_localizations_en.dart';
import 'app_localizations_ko.dart';

abstract class AppLocalizations {
  AppLocalizations(String locale) : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = <LocalizationsDelegate<dynamic>>[
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('ko'),
  ];

  String get cancel;
  String get save;
  String get confirm;
  String get delete;
  String get edit;
  String get done;
  String get close;
  String get apply;
  String get exit;
  String get add;
  String get create;
  String get irrevocable;
  String get editExitTitle;
  String get editExitContent;
  String get editComplete;
  String get saveChanges;
  String get deleteConfirmTitle;
  String deletePortfolioContent(String name);
  String deleteItemContent(String name);
  String get appExitTitle;
  String get appExitContent;
  String get neverUpdated;
  String get toastAutoSettingRequired;
  String updateFailed(String msg);
  String get updateSuccess;
  String get portfolioNotFound;
  String get additionalInvestment;
  String get currentAssets;
  String get rebalancingBase;
  String get remainingCash;
  String estimatedFee(String fee);
  String exchangeRateLabel(String rate);
  String weightWarning(String pct);
  String get labelSettings;
  String get labelEdit;
  String get labelGraph;
  String get labelRebalanceApply;
  String get addStock;
  String get buy;
  String get sell;
  String get hold;
  String get cash;
  String get rebalanceApplyTitle;
  String get rebalanceBullet1;
  String get rebalanceBullet2;
  String get savePermissionRequired;
  String get captureFailed;
  String get savedToGallery;
  String get saveFailed;
  String saveFailedError(String error);
  String get editCenterText;
  String get editItem;
  String get displayName;
  String get colorLabel;
  String get portfolioEmpty;
  String get portfolioGraph;
  String get editCompleteTooltip;
  String get editTooltip;
  String get editCompleteBeforeSave;
  String get saveImage;
  String get targetWeight;
  String get currentWeight;
  String get noPriceInfo;
  String get tapToEdit;
  String get dragToReorder;
  String get disclaimerTitle;
  String get disclaimerSectionPurpose;
  String get disclaimerTextPurpose;
  String get disclaimerSectionData;
  String get disclaimerTextData;
  String get disclaimerSectionRisk;
  String get disclaimerTextRisk;
  String get disclaimerSectionTax;
  String get disclaimerTextTax;
  String get disclaimerSectionService;
  String get disclaimerTextService;
  String get disclaimerDontShowAgain;
  String get disclaimerStartBtn;
  String get disclaimerConfirmBtn;
  String get editStockTitle;
  String get addStockTitle;
  String get cashItem;
  String get searchStock;
  String get searchHint;
  String get stockName;
  String get cashNameHint;
  String get autoFillHint;
  String get stockCodeTicker;
  String get currentPrice;
  String get autoUpdate;
  String get autoUpdateHint;
  String get targetWeightLabel;
  String get holdingsAmount;
  String get holdingsShares;
  String get unitUSD;
  String get unitKRW;
  String get unitShares;
  String get portfolioExampleHint;
  String get editPortfolioTitle;
  String get createPortfolioTitle;
  String get portfolioName;
  String get iconLabel;
  String get createBtn;
  String get settings;
  String get baseCurrency;
  String get currencyKRW;
  String get currencyUSD;
  String get amountDisplay;
  String get amountDisplayHint;
  String get fullDisplay;
  String get compactDisplay;
  String get tradingFee;
  String get includeFee;
  String get feeRate;
  String get exchangeRateSetting;
  String get autoRealtime;
  String get exchangeRateInput;
  String get autoRateHint;
  String get stockPriceSetting;
  String get autoPriceHint;
  String get language;
  String get langKorean;
  String get langEnglish;
  String get portfolioAddBtn;
  String itemCountLabel(int count);
  String get notice;
  String get lightMode;
  String get darkMode;
  String get currentPriceLabel;
  String get holdingsLabel;
  String get targetWeightRow;
  String get currentWeightRow;
  String get finalWeightRow;
  String get tradeRow;
  String wonEquivalent(String amount);
  String get autoPriceUpdateInfo;
  String get unitKrwSuffix;
  String get unitKrwMan;
  String get etfBadge;
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(lookupAppLocalizations(locale));
  }

  @override
  bool isSupported(Locale locale) => <String>['en', 'ko'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

AppLocalizations lookupAppLocalizations(Locale locale) {
  switch (locale.languageCode) {
    case 'en': return AppLocalizationsEn();
    case 'ko': return AppLocalizationsKo();
  }
  throw FlutterError('AppLocalizations.delegate failed to load unsupported locale "$locale"');
}
